### ISSUE TITLE
Alpine and multistage build

### ISSUE THREAD

**Issue by Wrede** [ScilifelabDataCentre/serve-images#55]
Recommendation:
Replace base images (especially ubuntu:<version>) with alpine base image where possible. This can reduce the image size considerably and minimize vulnerable packages. For example for an an python build use "python: 3.10.x-alpine".

Use multistage build to reduce size even further. For example separate build and runtime environments with multistage.
Our current studio image (still work in progress but managed to reduce size to 460mb from 1.75gb):
```
FROM python:3.8.10-alpine as base
LABEL maintainer="fredrik@scaleoutsystems.com"
WORKDIR /app
COPY requirements.txt .
RUN apk add --update --no-cache \
    build-base \
    python3-dev \
    py3-setuptools \
    postgresql-dev \
    libpq \
    jpeg-dev \ 
    openjpeg-dev \
    && pip install --no-cache-dir -r requirements.txt

FROM bitnami/kubectl:1.20.9 as kubectl
FROM alpine/helm:3.1.1 as helm

FROM python:3.8.10-alpine as build
COPY --from=base /usr/local/lib/python3.8/site-packages/ /usr/local/lib/python3.8/site-packages/
COPY --from=base /usr/local/bin/ /usr/local/bin/
COPY --from=kubectl /opt/bitnami/kubectl/bin/kubectl /usr/local/bin/
COPY --from=helm /usr/bin/helm /usr/local/bin/

RUN apk add --update --no-cache \
    sudo \
    bash \
    postgresql-client \
    libpq \
    jpeg-dev \ 
    openjpeg-dev \
    libpng-dev


# Set working directory
ARG USER=stackn
RUN adduser -D $USER \
        && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
        && chmod 0440 /etc/sudoers.d/$USER \
        && mkdir -p /app/media /app/charts/values && chown -R $USER /app/media/ app/charts/values

USER $USER
WORKDIR /app
COPY . /app/
```

**Comment by sandstromviktor** [comment]
Thanks @Wrede for your suggestions. We've been trying to build some alpine based images but run into much trouble with python packages as they sometimes need to be compiled from C-code. See  [this link](https://pythonspeed.com/articles/alpine-docker-python/).
We will look into multistage builds where possible.

**Comment by Wrede** [comment]
Ok maybe python-3.8-slim (blog is comparing slim and alpine, not ubuntu) work better in some cases, I have not noticed any problems so far with alpine but they might occur in the future.

**Comment by Wrede** [comment]
I agree that the builds are slower with alpine, but he does not seem to consider multistage builds in the blog. What one can do is use a build stage where one use a base image which comply with dependencies and build time, but then the final image uses COPY from the build stage.

**Comment by sandstromviktor** [comment]
@Wrede, great, we will look into that. If you see some image where a multistage build is obvious, please let us know. I tried this with RStudio, but it seemed to be very tricky since it is quite a complex image.

**Comment by sandstromviktor** [comment]
@Wrede, i tested your posted multistage build but i didn't work. I've made some modifications and this works for me, at least on a local microk8s and our own repo. Would you mind if we use this as our studio-build?

```code
FROM python:3.8.10-alpine as base
LABEL maintainer="fredrik@scaleoutsystems.com"

WORKDIR /app

COPY requirements.txt .
RUN apk add --update --no-cache \
    libffi-dev \
    build-base \
    python3-dev \
    py3-setuptools \
    postgresql-dev \
    libpq \
    jpeg-dev \ 
    zlib-dev \
    gcc \
    openjpeg-dev \
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

FROM bitnami/kubectl:1.20.9 as kubectl
FROM alpine/helm:3.1.1 as helm

FROM python:3.8.10-alpine as build
COPY --from=base /usr/local/lib/python3.8/site-packages/ /usr/local/lib/python3.8/site-packages/
COPY --from=base /usr/local/bin/ /usr/local/bin/
COPY --from=kubectl /opt/bitnami/kubectl/bin/kubectl /usr/local/bin/
COPY --from=helm /usr/bin/helm /usr/local/bin/

RUN apk add --update --no-cache \
    sudo \
    bash \
    postgresql-client \
    libpq \
    jpeg-dev \ 
    openjpeg-dev \
    libpng-dev


# Set working directory
COPY . /app/
WORKDIR /app
ARG USER=stackn
RUN adduser -D $USER \
        && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
        && chmod 0440 /etc/sudoers.d/$USER \
        && mkdir -p /app/media /app/charts/values \
        && chown -R $USER /app

USER $USER

```
