### ISSUE TITLE
MLFlow image

### ISSUE THREAD

**Issue by Wrede** [ScilifelabDataCentre/serve-images#63]
serve-mlflow I assume is only the mlflow server? Do you have an image for mlflow-serve, in other words serving a mlflow model? I think I shared the Dockerfile with you.

**Comment by alfredeen** [comment]
Hi, I did not work on the mlflow image but according to Viktor it should be both serve and server. There are pytests for both mlflow serve and server that pass. However he left a note that there is path issue in the helm chart that needs to be fixed.

**Comment by alfredeen** [comment]
OK, good to know. I will close the issue for now.
